######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 20 16:59:39 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
