######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 19 17:45:01 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CodeEditor.h highlighter.h MainWindow.h LineNumberArea.cpp
SOURCES += CodeEditor.cpp \
           demo.cpp \
           highlighter.cpp \
           LineNumberArea.cpp \
           MainWindow.cpp
